### ISSUE TITLE
Appeals should be to the IAB not the ISOC BoT

### ISSUE THREAD

**Issue by ekr** [intarchboard/program-rfced-future#36]
I have two reasons for this:

1. The ISOC BoT really isn't that closely tied to the RFC community.
2. We have barely (if any) experience with the ISOC BoT so let's not add this as the first time.

**Comment by martinthomson** [comment]
See #16.

I agree that ISOC BoT is a poor choice.

I would instead suggest that appeals of RSAB choices are taken to the bodies that appoint each RSAB member.  That is, if the actions of the IAB delegate are in question, then talk to the IAB; if it is the IESG delegate, take that up with the IESG.  If there are multiple people, take it up with each of the respective bodies separately.  Each of those bodies has their own higher authority also, so failed appeals can be escalated further in the extreme.

The basis for appeals though needs to be clear: this only occurs because the assertion is that the RSAB has not acted in the interest of their stream or that the process was not followed (unnecessary delays in producing a position, that sort of thing).

Appeals should be made to the body formally, with the RSAB being notified (either by the appellant or the body that receives the appeal, it matters not).  The appeal should be dealt with in a timely fashion (1 month seems appropriate).

I assume that this relates to approvals; if there are problems with chairs, I think that the logical appeal path is to the RSAB - or the body that appoints chairs.

**Comment by elear** [comment]
Reminder- pls take discussion to the list.

**Comment by elear** [comment]
General agreement to **not** use ISOC in appeals chain.

No agreement yet on what the appeals chain for the RSAB is.

**Comment by elear** [comment]
What is in the draft today:

>   Appeals of RSAB decisions shall be made to the IAB and should be made
   within thirty (30) days of public notice of the relevant RSAB
   decision (typically, when minutes are posted).  The appeals body
   shall decide whether a process failure occurred and what if any
   corrective action should take place.

I believe "appeals body" should be replaced with IAB as an editorial.

**Comment by stpeter** [comment]
ACK on the editorial change.

**Comment by elear** [comment]
@stpeter please close when you've made the editorial change.
