### ISSUE TITLE
When do the WG chairs call rough consensus and what happens next?

### ISSUE THREAD

**Issue by elear** [intarchboard/program-rfced-future#45]
Joel Halpern issue JMH5
Reading the process, I was struck by a minor gap in the process items.  specifically in item 4 on issueing the last call.  I think the text should include that the WG Chairs consider the proposal to be sufficiently developed and refined.  We sometimes have situations where there is rough consensus for something, but it really needs a little more work before it is sent out.  Obviously, we do not want to require perfection. But we do want to give the chairs room to say "this needs more work".

**Comment by elear** [comment]
o chairs call consensus
o chairs do their best to judge the actual rough consensus of the WG
o chairs are also expected to participate as individuals in the work of the WG
o chairs are expected to consider their own input as individuals along with all other input in judging rough consensus.

This language needs to be in the draft.

**Comment by stpeter** [comment]
I'll have text on this in the next version. I checked in a few changes to address this and can share it on list:

3. The RSWG shall then further develop the proposal. Members of the RSAB are expected to participate in discussion relating to such proposals so that they are fully aware of proposals early in the policy definition process and so that any issues or concerns that they have will be raised during the development of the proposals and will not be left until the RSAB review period. The RWSG chairs are also expected to participate as individuals.
5. At some point, if the RSWG chairs believe there may be rough consensus for the proposal to advance, they will issue a last call for comment within the working group.
5. After a comment period of suitable length, the RSWG chairs will determine whether rough consensus for the proposal exists (taking their own feedback as individuals into account along with feedback from other participants). If comments have been received and substantial changes have been made, it is expected that additional last calls may be necessary.
