### ISSUE TITLE
Communicating decisions about RPC projects/priorities to the community

### ISSUE THREAD

**Issue by JayDaley** [intarchboard/program-rfced-future#62]
It is not clear who would communicate decisions about RPC projects/priorities to the community.

**Comment by elear** [comment]
This is the work program.  Comments from #61 are applicable.  Key point from Mirja: be careful not to overspecify in this document.  ALSO- a comment from Mike:

> there is no RSWG cognizant work program - its an LLC/RPC thing. Things get added to that after RFC completion, and LLC funding determination, and RPC agreement to execute.

**Comment by elear** [comment]
Also from Mike:

> Michael StJohns
*sigh* New question - here just because I don't want to forget: Does either of the RSAB/RSWG have any input in the priority of the processing effort (within the RPC) of specific documents? If there are disagreement between the stream managers as to such priority, who resolves the disagreements?

Paraphrasing Jay: there's some text for that.
